name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  housekeeping:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.25']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Download dependencies
      run: go mod tidy
    
    - name: Verify dependencies
      run: go mod verify
    
    - name: Build
      run: go build -v ./...
    
    - name: Run tests (if any exist)
      run: |
        if find . -name "*_test.go" | grep -q .; then
          go test -v -race ./...
        else
          echo "No tests found, skipping test execution"
        fi